services:
  backend:
    container_name: backend-Express
    ports: 
      - '3000:3000'
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    extra_hosts:
    - "host.docker.internal:host-gateway"